config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    devise_scope :user do
        get 'login', to: 'devise/sessions#new'
        get 'logout', to: 'devise/sessions#destroy'
        get 'signup', to: 'devise/registrations#new'
    end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'pages#home'
    get 'about', to: 'pages#about'
    get 'contact', to: 'pages#contact'

    # Custom events routes
    get 'events/hackathon-2020', to: 'articles#hackathon2020'

    resources :articles, path: 'events'

    resources :users, except: [:new, :show]
    get ':id', to: 'users#show'

    # Commented :users out as Devise is handling it
    # get 'signup', to: 'users#new'

    # get 'login', to: 'sessions#new'
    # post 'login', to: 'sessions#create'
    # delete 'logout', to: 'sessions#destroy'
end

app/models/article.rb
class Article < ApplicationRecord
    # Added FriendlyId functionality:
    # This allows article ('event') paths to be displayed by title name
    extend FriendlyId
    friendly_id :title, use: :slugged

    belongs_to :user
    validates :title, presence: true, length: {minimum: 1, maximum: 30}
    validates :description, presence: true, length: {minimum: 1, maximum: 300}
    validates :user_id, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_action :set_article, only: [:edit, :update, :show, :destroy]
before_action :require_user, only: [:create, :edit, :update, :destroy]
before_action :require_permissions, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 7)

  end

  def new
    @article = Article.new
  end

  def edit

  end

  def create
    # render plain: params[:Article].inspect
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Event was successfully created"
      redirect_to articles_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Event was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article successfully deleted"
    redirect_to articles_path
  end

  def hackathon2020
  end

  private
    def article_params
      params.require(:article).permit(:title, :description, :user_id, :start_time, :start_date)
    end

    def set_article
      @article = Article.friendly.find(params[:id])
    end

    def require_permissions
      if @article.user != current_user && !admin?
        flash[:danger] = "You do not have permissions to perform that action"
        redirect_back(fallback_location: articles_path)
      end
    end
end

app/views/articles/_form.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form", autocomplete: "off"}) do |f| %>
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :title %> <br>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, placeholder: "Enter title", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :description %> <br>
        </div>
        <div class="col-sm-8">
          <%= f.trix_editor :description, placeholder: "Event Description",
           style: "overflow-y: auto; max-height:800px; height: 175px;", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
          <div class="col-sm-2 control-label">
              Date
          </div>
          <div class="col-sm-8" style="color:black;">
              <%= f.date_select :start_date %>
          </div>
      </div>

      <div class="form-group">
          <div class="col-sm-2 control-label">
              Time
          </div>
          <div class="col-sm-8" style="color:black;">
              <%= f.time_select :start_time, {ampm: true} %>
          </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: "btn btn-primary btn-lg"%>
          <%= link_to "Cancel", :back, class: "btn btn-lg btn-danger" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= render "shared/errors", obj: @article %>

app/views/articles/_list_new_articles.html.erb
<% obj.each do |article| %>
    <% if !article.start_date.to_date.past? %>
        <div class="col-xs-8 col-xs-offset-2">
          <div class="well well-lg">
            <div class="article-title">
              <%= link_to "#{article.title}", article_path(article) %>
            </div>
            <div class="article-body">
              <%= truncate(sanitize(article.description, tags:[]), length:110) %>
            </div>
            <div class="article-body">
                When: <%= article.start_date.strftime("%B %d, %Y") %> at <%= article.start_time.in_time_zone("PST8PDT").strftime("%I:%M%p") %>
            </div>
            <div class="article-meta">
              <small>
                <%= if article.user then p "Created by #{article.user.username} | " end %>
                Created <%= time_ago_in_words(article.created_at) %> ago |
                Modified <%= time_ago_in_words(article.updated_at) %> ago
              </small>
            </div>
            <% if user_signed_in? %>
              <div class="article-actions">
                <%= link_to "Edit", edit_article_path(article),
                class: "btn btn-sm btn-primary" %>
                <%= link_to "Delete", article_path(article),
                class: "btn btn-sm btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
              </div>
            <% end %>
          </div>
        </div>
    <% end %>
<% end %>

app/views/articles/_list_past_articles.html.erb
<% obj.each do |article| %>
    <% if article.start_date.to_date.past? %>
        <div class="col-xs-8 col-xs-offset-2">
          <div class="well well-lg">
            <div class="article-title">
              <%= link_to "#{article.title}", article_path(article) %>
            </div>
            <div class="article-body">
              <%= truncate(sanitize(article.description, tags:[]), length:110) %>
            </div>
            <div class="article-body">
                When: <%= article.start_date.strftime("%B %d, %Y") %> at <%= article.start_time.in_time_zone("PST8PDT").strftime("%I:%M%p") %>
            </div>
            <div class="article-meta">
              <small>
                <%= if article.user then p "Created by #{article.user.username} | " end %>
                Created <%= time_ago_in_words(article.created_at) %> ago |
                Modified <%= time_ago_in_words(article.updated_at) %> ago
              </small>
            </div>
            <% if user_signed_in? %>
              <div class="article-actions">
                <%= link_to "Edit", edit_article_path(article),
                class: "btn btn-sm btn-primary" %>
                <%= link_to "Delete", article_path(article),
                class: "btn btn-sm btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
              </div>
            <% end %>
          </div>
        </div>
    <% end %>
<% end %>

app/views/articles/edit.html.erb
<h1 align="center">Edit Event</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align='center' style='margin-bottom: .5em;
text-shadow: 2px 2px black'>Upcoming Events</h1>

<% upcoming = false %>
<% @articles.each do |article| %>
<% if !article.start_date.to_date.past? %>
<% upcoming = true %>
<% end %>
<% end %>

<% if upcoming == false %>
<div class="col-xs-8 col-xs-offset-2" style="margin-bottom:2em">
<center>No upcoming events at this time!</center>
</div>
<% end %>

<div align="center">

</div>

<%= render "/articles/list_new_articles", obj: @articles %>

<%= will_paginate %>
<div class="col-xs-8 col-xs-offset-2">
    <h1 align='center' style='margin-bottom: .5em;'>Past Events</h1>
</div>

<%= render "/articles/list_past_articles", obj: @articles %>

<div align="center">
    <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center"
style='color:antiquewhite; text-shadow: 2px 2px black;'>Create an Event</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h1 align=center><%= @article.title %></h1>

<div style="margin-top:2em;"></div>
<div class="col-md-offset-2">
    <div class="card col-md-2 well">
        <h4>Date</h4>
        <h6 class="text-muted">
            <%= raw(@article.start_date.strftime("%B %d, %Y")) %>
            <br>
            <%= raw(@article.start_time.in_time_zone("PST8PDT").strftime("%I:%M%p")) %>
        </h6>
    </div>
    <div class="col-md-8">
        <%= raw(@article.description) %>
    </div>

</div>

<div class="col-xs-offset-3">

</div>

<div class="col-xs-8 col-xs-offset-2">

    <% if user_signed_in? %>
    <p align="center">
        <%= link_to "Edit", edit_article_path(@article), class: "btn btn-md btn-primary", style: "width: 8.8em;" %>
        <%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-md btn-danger", style: "width: 10em;" %>
    </p>
    <% end %>

    <p align="center">
        <%= link_to "Back", articles_path, class: "btn btn-md btn-primary" %>
    </p>

</div>