config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    devise_scope :user do
        get 'login', to: 'devise/sessions#new'
        get 'logout', to: 'devise/sessions#destroy'
        get 'signup', to: 'devise/registrations#new'
    end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'pages#home'
    get 'about', to: 'pages#about'
    get 'contact', to: 'pages#contact'

    # Custom events routes
    get 'events/hackathon-2020', to: 'articles#hackathon2020'

    resources :articles, path: 'events'

    resources :users, except: [:new, :show]
    get ':id', to: 'users#show'

    # Commented :users out as Devise is handling it
    # get 'signup', to: 'users#new'

    # get 'login', to: 'sessions#new'
    # post 'login', to: 'sessions#create'
    # delete 'logout', to: 'sessions#destroy'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :confirmable, # removed registerable
         :recoverable, :rememberable, :validatable

  # Reference to Article model
  has_many :articles, dependent: :destroy

  # before_save { self.email = email.downcase }
  # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # validates :email, presence: true, uniqueness: {case_sensitive: false},
  #           length: {minimum: 3},
  #           format: {with: VALID_EMAIL_REGEX}
  # validates :password, presence: true
  validates :username, presence: true, uniqueness: {case_sensitive: false},
            length: {minimum: 3}

  # Has one profile photo attached
  has_one_attached :avatar
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :destroy_photo]
  before_action :require_permissions, only: [:index, :show, :edit]

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page], per_page: 7)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "Welcome to Click-Feed  #{@user.username}!"
      session[:user_id] = @user.id
      redirect_to "/#{@user.id}"
    else
      render 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user, :bypass => true)
        format.html { redirect_to "/#{@user.id}" }
        flash[:success] = "Your profile was successfully updated."
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    session[:user_id] = nil if current_user == @user
    respond_to do |format|
      format.html { redirect_to users_path }
      flash[:danger] = "#{@user.username} and their articles were successfully deleted."
      format.json { head :no_content }
    end
  end

  def destroy_photo
      @user.avatar.purge
      respond_to do |format|
        format.html { redirect_to "/#{@user.id}" }
        flash[:success] = "Your profile photo has been successfully deleted."
        format.json { head :no_content }
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :admin, :avatar)
    end

    def require_permissions
      if (@user != current_user && !admin?) || !user_signed_in?
        flash[:danger] = "You do not have permissions to perform that action"
        redirect_back(fallback_location: root_path)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form", autocomplete: "off"}) do |f| %>
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :username %> <br>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, placeholder: "Enter username", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :email %> <br>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email, placeholder: "Enter email", rows: 10, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :password %> <br>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password, placeholder: "Enter password", rows: 10, class: "form-control" %>
        </div>
      </div>

      <% if admin? %>
        <div class="form-group">
          <div class="col-sm-2 control-label">
            <%= f.label :admin %> <br>
          </div>
          <div class="col-sm-8">
            <%= f.check_box :admin %>
          </div>
        </div>
      <% end %>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit @user.new_record? ? "Sign up" : "Update account", class: "btn btn-primary btn-lg" %>
          <%= link_to 'Back', :back, class: "btn btn-md" %>
          <%= link_to "Delete User", user_path(@user), method: :delete, class: "btn btn-md",
                      data: {confirm: "Are you sure you want to perform this action? This will delete the user and all data. This action cannot be undone."},
                      style: "text-align:right; color: red" if !user.new_record? %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= render "shared/errors", obj: @user %>

app/views/users/_list_users.html.erb
<% obj.each do |user| %>
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
            <% if user.avatar.attached? %>
            <div class="avatar-window" style="margin-left:0; margin-bottom:10px;">
                <%= link_to image_tag("#{(url_for(user.avatar))}", class: "avatar-window"), "/#{user.id}" %>
            </div>
            <% end %>
            <div class="article-title">
                <%= link_to "#{user.username}", "/#{user.id}" %>
            </div>
            <% if user.admin %>
            <div class="article-meta">
                <small>
                    Administrator
                </small>
            </div>
            <% end %>
            <% if (user == current_user && user_signed_in?) || admin? %>
            <div class="article-actions">
                <%= link_to "Edit", "/#{user.id}", class: "btn btn-sm btn-primary" %>
                <%= link_to "Delete", user_path(user), class: "btn btn-sm btn-danger", method: :delete, data: {confirm: "Are you sure you want to perform this action? This will delete the user and all data. This action cannot be undone"} %>
            </div>
            <% end %>
        </div>
    </div>
</div>
<% end %>

app/views/users/edit.html.erb
<h1 style="text-align:center; margin-bottom:80px;">Edit Your Account</h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<h1 align='center' style='margin-bottom: .5em;'>Users List</h1>

<div align="center">
  <%= will_paginate %>
</div>

<%= render "/users/list_users", obj: @users %>

<div align="center">
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Sign Up</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<h1 style="text-align:center; margin-bottom:80px;">Profile</h1>

<div class="row">
    <div class="well col-md-3 col-md-offset-2" style="text-align:center;">
        <div class="avatar-window">
            <% if @user.avatar.attached? %>
            <img src="<%=(url_for(@user.avatar))%>">
            <div class="avatar-window add-photo">
                <%= button_to "Delete Photo", destroy_photo_path(@user),
                method: :get, class: "btn btn-danger btn-sm",
                data: {confirm: "Are you sure you want to delete this photo? This action cannot be undone."} %>
            </div>
            <% else %>
            <img src="/assets/emptyavatar.png" alt="">
            <div class="avatar-window add-photo">
                <!-- Button trigger modal -->
                <button class="btn btn-primary btn-md" data-toggle="modal" data-target="#normal">
                    Add Photo
                </button>
            </div>
            <% end %>
        </div>
        <br>
        <br>

        <div class="btn btn-primary">
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        </div>

        <br>
        <br>
        <p><%= @user.username %></p>
    </div>

    <div class="col-md-5 col-md-offset-1" style="margin-top:10px;">
        <p>
            <strong>Username:</strong>
            <%= @user.username %>
        </p>
        <p>
            <strong>Email:</strong>
            <%= @user.email %>
        </p>
        <p>
            <strong>Status:</strong> <%= @user.creator? ? "Creator (y)!" : "The Best" %>
        </p>

        <div class="article-actions" style="padding-top:25px;">
            <% if (current_user == @user && user_signed_in?) || admin? %>
            <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-sm btn-primary" %>
            <% end %>
            <% if admin? %>
            <%= link_to "Back to all users", users_path, class: "btn btn-sm btn-primary" %>
            <% end %>
        </div>
        <div class="article-actions" style="padding-top:25px;">
            <%= link_to "Click to Feed!", "/#{@user.id}/feed", class: "btn btn-lg btn-primary" if @user.creator? %>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="normal" tabindex="-1" role="dialog" aria-labelledby="approvalModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">Upload Profile Photo</h4>
            </div>
            <div class="modal-body">
                <%= form_for(@user, :html => {class: "form-horizontal", role: "form", autocomplete: "off"}) do |f| %>
                <%= f.label "Profile Photo" %>
                <%= f.file_field :avatar %>
            </div>
            <div class="modal-footer">
                <%= submit_tag "Upload", name: nil, class: "btn btn-primary" %>
                <% end %>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->