config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    devise_scope :user do
        get 'login', to: 'devise/sessions#new'
        get 'logout', to: 'devise/sessions#destroy'
        get 'signup', to: 'devise/registrations#new'
    end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'pages#home'
    get 'about', to: 'pages#about'
    get 'contact', to: 'pages#contact'

    # Custom events routes
    get 'events/hackathon-2020', to: 'articles#hackathon2020'

    resources :articles, path: 'events'

    resources :users, except: [:new, :show]
    get ':id', to: 'users#show'

    # Commented :users out as Devise is handling it
    # get 'signup', to: 'users#new'

    # get 'login', to: 'sessions#new'
    # post 'login', to: 'sessions#create'
    # delete 'logout', to: 'sessions#destroy'
end

app/views/layouts/_footer.html.erb
<div class="footer col-sm-2 col-sm-offset-5">
    <% if !user_signed_in? %>
    <%= link_to "Site Admin Login", new_user_session_path, style: "color:#777;" %>
    <% else %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete, style: "color:#777;" %>
    <% end %>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% if flash.any? %>
      <br>
    <% end %>
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= "#{name}" %>">
        <!-- <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> -->
        <%# <%= msg %>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li></li>
                <li class="dropdown">

                    <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">One more separated link</a></li>
                </ul>-->
            </li>
        </ul>
        <!-- Search bar
        <form class="navbar-form navbar-left">
        <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
</form> -->
<ul class="nav navbar-nav navbar-right">
    <li><%= link_to "Home", root_path %></li>
    <li> <%= link_to "Events", articles_path %> </li>
    <li> <%= link_to "About", about_path %> </li>
    <li> <%= link_to "Contact", contact_path %> </li>
  
    <% if user_signed_in? %>
    <li> <%= link_to "Create Event", new_article_url %> </li>
    <% end %>
    <% if user_signed_in? %>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%= current_user.username %> <%= p "(admin)" if admin? %> <span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li> <%= link_to "View Profile", "/#{current_user.id}" %> </li>
            <li> <%= link_to "Users Admin", users_path if admin? %> </li>
            <li role="separator" class="divider"></li>
            <li> <%= link_to "Logout", destroy_user_session_path, method: :delete %> </li>
        </ul>
    </li>
    <% end %>



    <!-- Dropdown
    <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
    <ul class="dropdown-menu">
    <li><a href="#">Action</a></li>
    <li><a href="#">Another action</a></li>
    <li><a href="#">Something else here</a></li>
    <li role="separator" class="divider"></li>
    <li><a href="#">Separated link</a></li>
</ul>
</li> -->
</ul>
</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BCS Students Association" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#<%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%#<%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%#<%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%#<%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'bcsicon.png', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->

</head>
<body>

    <%= render "/layouts/navigation" %>

    <div class="container">
        <div class="row">
            <%= bootstrap_flash %>
            <%= yield %>
        </div><!--/row-->


    </div> <!-- /container -->
    <%= render "/layouts/footer" %>
</body>
</html>